---
title: "Untitled"
output: html_document
date: "2023-01-08"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
cat("\014")
rm(list = ls(all = TRUE))
```

```{r}
load("C:/Users/wjyjy/Documents/TDA/Mandibular Molars/alignment_ECT/Tarsius.RData")
Tarsius = data
load("C:/Users/wjyjy/Documents/TDA/Mandibular Molars/alignment_ECT/Microcebus.RData")
Microcebus = data
```

```{r}
number_iterations =11
number_directions = 2918
grid_length = 200
T=3
```

```{r}
ECT_1_list=list()
for (i in 1:number_iterations) {
  ECT_1_list[[i]]=t(Tarsius[[i]])
}

ECT_2_list=list()
for (i in 1:number_iterations) {
  ECT_2_list[[i]]=t(Microcebus[[i]])
}
```


```{r}
    t_grid=seq(from=0, to=T, length.out = grid_length)
    SECT_1_list=list()
    ECT=matrix(NA, ncol = number_directions, nrow = grid_length)
    for (iterations in 1:number_iterations) {
    
    
    ECT_2D_results=ECT_1_list[[iterations]]
    PECT=matrix(NA, ncol = number_directions, nrow = grid_length)
    for (i in 1:dim(ECT_2D_results)[2]) {
      PECT[,i]=(T/grid_length)*cumsum(ECT_2D_results[,i])
    }
    
    PECT_2D_results=PECT
    SECT=matrix(NA, ncol = number_directions, nrow = grid_length)
    for (i in 1:dim(PECT_2D_results)[2]) {
      SECT[,i]=PECT_2D_results[,i]-(PECT_2D_results[dim(PECT_2D_results)[1],i]/T)*t_grid
    }
    
    SECT_1_list[[iterations]]=SECT
  }
```


```{r}
    t_grid=seq(from=0, to=T, length.out = grid_length)
    SECT_2_list=list()
    ECT=matrix(NA, ncol = number_directions, nrow = grid_length)
    for (iterations in 1:number_iterations) {
    
    
    ECT_2D_results=ECT_2_list[[iterations]]
    PECT=matrix(NA, ncol = number_directions, nrow = grid_length)
    for (i in 1:dim(ECT_2D_results)[2]) {
      PECT[,i]=(T/grid_length)*cumsum(ECT_2D_results[,i])
    }
    
    PECT_2D_results=PECT
    SECT=matrix(NA, ncol = number_directions, nrow = grid_length)
    for (i in 1:dim(PECT_2D_results)[2]) {
      SECT[,i]=PECT_2D_results[,i]-(PECT_2D_results[dim(PECT_2D_results)[1],i]/T)*t_grid
    }
    
    SECT_2_list[[iterations]]=SECT
  }
```


```{r}
  ###############################################################
  ### Compute the mean functions of the two SECT collections
  ###############################################################
  
  M_1=SECT_1_list[[1]]
  for (i in 2:number_iterations) {
    M_1=M_1+SECT_1_list[[i]]
  }
  M_1=(1/number_iterations)*M_1
  M_2=SECT_2_list[[1]]
  for (i in 2:number_iterations) {
    M_2=M_2+SECT_2_list[[i]]
  }
  M_2=(1/number_iterations)*M_2
  
  
  ###############################################################
  ### Select the distinguishing direction
  ###############################################################
  
  supnorm=vector()
  for (directions in 1:number_directions) {
    supnorm[directions]=max(abs(M_1[,directions]-M_2[,directions]))
  }
  distinguishing_direction_index=max(which.max(supnorm))
  
  
  ###############################################################
  ### Karhunen-Loeve decomposition
  ###############################################################
  
  SECT_1_distinguishing_direction=matrix(NA, ncol = number_iterations, nrow = grid_length)
  for (i in 1:number_iterations) {
    SECT_1_distinguishing_direction[,i]=SECT_1_list[[i]][, distinguishing_direction_index]
  }
  SECT_2_distinguishing_direction=matrix(NA, ncol = number_iterations, nrow = grid_length)
  for (i in 1:number_iterations) {
    SECT_2_distinguishing_direction[,i]=SECT_2_list[[i]][, distinguishing_direction_index]
  }
  
  demean_all=matrix(NA, ncol = 2*number_iterations, nrow = grid_length)
  for (i in 1:number_iterations) {
    demean_all[,i]=SECT_1_distinguishing_direction[,i]-M_1[, distinguishing_direction_index]
  }
  for (i in 1:number_iterations) {
    demean_all[,number_iterations+i]=SECT_2_distinguishing_direction[,i]-M_2[, distinguishing_direction_index]
  }
  
  CovKer=cov(t(demean_all))
  eigen_results=eigen(CovKer)
  result <- pmax(eigen_results$values, 0)

  # We only care about the components having 95% cumulative variance.
  L=max(which(cumsum(result)/sum(result)<0.98))
  Eigen_values=(T/grid_length)*result[1:L]
  Eigen_vectors=sqrt(grid_length/T)*eigen_results$vectors[,1:L]
  
  Xis=matrix(NA, ncol = L, nrow = number_iterations)
  for (i in 1:number_iterations) {
    Xi=vector()
    for (l in 1:L) {
      Xi[l]=(1/sqrt(2*Eigen_values[l]))*(T/grid_length)*sum((SECT_1_distinguishing_direction[,i]-SECT_2_distinguishing_direction[,i])*Eigen_vectors[,l])
    }
    Xis[i,]=Xi
  }
  
  chisq_statistic_seq=sum((sqrt(number_iterations)*apply(Xis, 2, mean))^2)
  df_seq=L
  p_value_seq=1-pchisq(sum((sqrt(number_iterations)*apply(Xis, 2, mean))^2), df=L)
  
  print(p_value_seq)
  



###############################################################
### Rejection rate with alpha = 0.05
###############################################################

mean(p_value_seq<0.05)

```
